Dhlavacd
ViaQ/Relp pull request #14
Opened 2017-08-31 11:53 UTC by dhlavac

Added TLS support and some protocol changes

2017-08-31 11:55 UTC, dhlavac commented
@jvymazal @radosroka  Please, look at that and try to test that

2017-09-06 11:32 UTC, jvymazal requested changes
Could you add something to changelog as well?
If you are making a major release this should be at least mentioned somewhere, better with justification why it was needed and what the backwards-(in)compatible changes are.

2017-09-06 11:32 UTC, jvymazal commented on lib/relp/server.rb
> +    def initialize(port, callback, host = '0.0.0.0' , tls_context = nil, logger = nil)
Why changing previous parameter order?

2017-09-19 16:13 UTC, dhlavac commented
@jvymazal Changes done

2017-10-17 14:00 UTC, jvymazal approved these changes

2017-10-17 14:01 UTC, merged